#!/usr/bin/python

from pynput import keyboard
import os

# The key combination to check
# More than one combination of keys can be added here 
key_combinations = [
    {keyboard.Key.shift, keyboard.Key.ctrl}
]

# The currently active modifiers
current = set()

# Indicates command execute on release
execute_cmd = False

# Command to execute
cmd = "xkb-switch -n"

def execute():
    global cmd

    os.system(cmd)    

def on_press(key):
    global execute_cmd

    if any([key in combo for combo in key_combinations]):
        current.add(key)
        if any(all(k in current for k in combo) for combo in key_combinations):
            execute_cmd = True
    else:
        current.clear()
        execute_cmd = False

def on_release(key):
    global execute_cmd

    if any([key in combo for combo in key_combinations]):
            if key in current:
                current.remove(key)
            if len(current) == 0 and execute_cmd:
                execute()
                execute_cmd = False

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
